# use command in Docker-compose.yml's folder:
## docker compose up
## docker compose down

version: '3.8'

services:

  python-docker:
    build: .

    volumes:
      - pytest_docker_data:/usr/src/app/reports/

    container_name: pythonds3

    restart: on-failure

    # # For testing only... Purpose: See how the directory is organized
    # ## At the moment, 
    # command: ["ls"]

    # primary command
    ## "--lf": runs failed tests first
    ## "l": lists variables and their assigned values
    command: ["pytest", "-v", "--lf", "-l", "--suppress-tests-failed-exit-code", "--continue-on-collection-errors","--junitxml=reports/results.xml"]
  
volumes:
  pytest_docker_data: